name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Detekt
        run: ./gradlew detekt --stacktrace

      - name: Check
        run: ./gradlew check --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Publish to Staging
        run: ./gradlew plot:publishReleasePublicationToSonatypeRepositor --stacktrace

      - name: Release to Production
        run: ./gradlew closeAndReleaseSonatypeStagingRepository --stacktrace
